### ISSUE TITLE
--lang is broken

### ISSUE THREAD

**Issue by DO1JLR** [bjesus/wttrbar#59]
Hey there, I tried to run your script with the --lang parameter and that happened:
```bash
 $ RUST_BACKTRACE=1 ./Downloads/wttrbar --lang de
thread 'main' panicked at src/main.rs:116:14:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: wttrbar::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```bash
 $ RUST_BACKTRACE=full ./Downloads/wttrbar --lang de
thread 'main' panicked at src/main.rs:116:14:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7faa94f012a5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h56c396e6ec1a6d25
   1:     0x7faa94f3fc1b - core::fmt::write::h8d9f62e4196a6251
   2:     0x7faa94efe76f - std::io::Write::write_fmt::hfeda4b672809964d
   3:     0x7faa94f0107e - std::sys_common::backtrace::print::h92792842c9200fcf
   4:     0x7faa94f02339 - std::panicking::default_hook::{{closure}}::h4fa40162feafd3ea
   5:     0x7faa94f0207d - std::panicking::default_hook::h5a52bd4fbc34f99c
   6:     0x7faa94f027d3 - std::panicking::rust_panic_with_hook::h33e85abbf3f92159
   7:     0x7faa94f0267b - std::panicking::begin_panic_handler::{{closure}}::h6e89e0968a11dcc7
   8:     0x7faa94f01769 - std::sys_common::backtrace::__rust_end_short_backtrace::h6f80b72bde67d6fa
   9:     0x7faa94f023e7 - rust_begin_unwind
  10:     0x7faa94c574f3 - core::panicking::panic_fmt::hb37c2646452904e3
  11:     0x7faa94c5759c - core::panicking::panic::h05304d7a92564453
  12:     0x7faa94c57499 - core::option::unwrap_failed::hb68718cdc2e283e0
  13:     0x7faa94c5bdf7 - wttrbar::main::hecbade2d690cd418
  14:     0x7faa94c76a83 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2c645147f358c919
  15:     0x7faa94c71e19 - std::rt::lang_start::{{closure}}::h578a143f751f65ad
  16:     0x7faa94ef915d - std::rt::lang_start_internal::ha99684538b0582d2
  17:     0x7faa94c5c735 - main
```

Don't know what is broken. Feel free to close the issue :wink:

**Comment by bjesus** [comment]
can you try to remove the temporary wttrbar file first? `rm /tmp/wttrbar*` ?

**Comment by DO1JLR** [comment]
thanks, that helped. sorry.

**Comment by bjesus** [comment]
I'm glad it helped! I'll leave the ticket open because wttrbar shouldn't crash like that anyway

**Comment by adocampo** [comment]
Just to mention it's still present as for today.

Workaround works, though

**Comment by bjesus** [comment]
@adocampo can you be more descriptive? what issue are you seeing exactly?
